export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#47475d",
        "on-error": "#690005",
        "surface-container-low": "#161d1f",
        "surface-container-high": "#242b2d",
        "surface-tint": "#47d6ff",
        "tertiary-fixed": "#b6ebff",
        "surface-dim": "#0e1416",
        "primary-fixed": "#b6ebff",
        "on-secondary-fixed-variant": "#45455b",
        "surface-variant": "#2f3638",
        "outline": "#929097",
        "on-background": "#dde4e6",
        "outline-variant": "#47464c",
        "primary": "#47d6ff",
        "tertiary-fixed-dim": "#47d6ff",
        "surface-container-highest": "#2f3638",
        "on-tertiary-fixed-variant": "#004e60",
        "on-tertiary": "#003543",
        "on-primary-fixed": "#001f28",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "secondary": "#c6c4df",
        "on-secondary-fixed": "#1a1a2e",
        "on-primary-container": "#0090b0",
        "primary-container": "#001f28",
        "surface-bright": "#333a3c",
        "on-tertiary-container": "#0090af",
        "secondary-fixed-dim": "#c6c4df",
        "surface-container": "#1a2123",
        "on-primary": "#003543",
        "on-tertiary-fixed": "#001f28",
        "on-secondary": "#2f2e43",
        "secondary-fixed": "#e2e0fc",
        "background": "#0e1416",
        "tertiary-container": "#001f28",
        "surface-container-lowest": "#080f11",
        "on-surface": "#dde4e6",
        "on-secondary-container": "#b8b6d0",
        "tertiary": "#47d6ff",
        "on-primary-fixed-variant": "#004e60",
        "on-surface-variant": "#c8c5cd",
        "primary-fixed-dim": "#47d6ff",
        "error": "#ffb4ab",
        "surface": "#0e1416",
        "inverse-on-surface": "#2b3234",
        "inverse-surface": "#dde4e6",
        "inverse-primary": "#00677f"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
